# Generated by Django 5.2.4 on 2025-08-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(storage='accounts/profile_images', upload_to=''),
        ),
    ]
