# Generated by Django 5.2.4 on 2025-07-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='library', to='relationship_app.library')),
            ],
        ),
    ]
